### ISSUE TITLE
Can't Pickle or Save resulting Models

### ISSUE THREAD

**Issue by alexmlamb** [zhoudaxia233/EfficientUnet-PyTorch#2]
`Traceback (most recent call last):
  File "run.py", line 17, in <module>
    torch.save(model, 'model.pt')
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 297, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'EfficientNet.encoder.<locals>.Encoder'
`

**Comment by zhoudaxia233** [comment]
@alexmlamb Hello Alex, you can try to save the weights using `torch.save(model.state_dict(), PATH)`.
